Add initial implementation of memory readout and interrupt handling

diff --git a/epics/runioc b/epics/runioc
--- a/epics/runioc
+++ b/epics/runioc
@@ -7,8 +7,27 @@ IOC=bin/linux-x86_64/lmbf
 HW_CONFIG=hardware_delays
 SYS_CONFIG=system_config
 DEV_ADDR=0000:04:00.0
+DEBUG=
+
+while getopts 'vh-' option; do
+    case "$option" in
+        v)  DEBUG=valgrind ;;
+        h)  cat <<EOF
+Usage: runioc [options]
+Starts LMBF IOC with configured options.
+    -v      Run with valgrind memory checker enabled
+    --      Pass further options on to IOC
+EOF
+            exit 0;;
+        -)  break ;;
+        *)  echo >&2 'Invalid option: try -h for help'
+            exit 1 ;;
+    esac
+done
+shift $((OPTIND-1))
+
 
 DEV_PREFIX=/dev/amc525_lmbf/pci-"$DEV_ADDR"/amc525_lmbf
 
-exec valgrind $IOC \
+exec $DEBUG $IOC \
     -H "$HW_CONFIG" -S "$SYS_CONFIG" -p "$DEV_PREFIX" "$@"
